using System;
using System.Collections.Generic;
public class WorldCapitalsItem
{
    public double Population { get; set; }
    public double Y { get; set; }
    public double X { get; set; }
    public string Country { get; set; }
    public string Name { get; set; }
}

public class WorldCapitals
    : List<WorldCapitalsItem>
{
    public WorldCapitals()
    {
        this.Add(new WorldCapitalsItem() { Population = 23.62, Y = 35.68, X = 139.81, Country = @"Japan", Name = @"Tokyo" });
        this.Add(new WorldCapitalsItem() { Population = 15.85, Y = 37.54, X = 126.94, Country = @"South Korea", Name = @"Seoul" });
        this.Add(new WorldCapitalsItem() { Population = 14.1, Y = 19.43, X = -99.13, Country = @"Mexico", Name = @"Mexico City" });
        this.Add(new WorldCapitalsItem() { Population = 13.1, Y = 55.75, X = 37.7, Country = @"Russia", Name = @"Moscow" });
        this.Add(new WorldCapitalsItem() { Population = 11.1, Y = 51.49, X = -0.18, Country = @"UK", Name = @"London" });
        this.Add(new WorldCapitalsItem() { Population = 10.75, Y = -34.67, X = -58.41, Country = @"Argentina", Name = @"Buenos Aires" });
        this.Add(new WorldCapitalsItem() { Population = 9.78, Y = 48.88, X = 2.43, Country = @"France", Name = @"Paris" });
        this.Add(new WorldCapitalsItem() { Population = 9.3, Y = 30.08, X = 31.25, Country = @"Egypt", Name = @"Cairo" });
        this.Add(new WorldCapitalsItem() { Population = 8.6, Y = -6.29, X = 106.76, Country = @"Indonesia", Name = @"Jakarta" });
        this.Add(new WorldCapitalsItem() { Population = 6.45, Y = 13.75, X = 100.55, Country = @"Thailand", Name = @"Bangkok" });
        this.Add(new WorldCapitalsItem() { Population = 6.45, Y = 39.91, X = 116.39, Country = @"China", Name = @"Beijing" });
        this.Add(new WorldCapitalsItem() { Population = 6.4, Y = 35.77, X = 51.45, Country = @"Iran", Name = @"Tehran" });
        this.Add(new WorldCapitalsItem() { Population = 6.13, Y = 25.04, X = 121.51, Country = @"Taiwan", Name = @"Taipei" });
        this.Add(new WorldCapitalsItem() { Population = 5.47, Y = 14.55, X = 121.17, Country = @"Philippines", Name = @"Manila" });
        this.Add(new WorldCapitalsItem() { Population = 5.4, Y = 22.43, X = 114.15, Country = @"UK", Name = @"Hong Kong" });
        this.Add(new WorldCapitalsItem() { Population = 5.06, Y = 52.52, X = 13.33, Country = @"Germany", Name = @"Berlin" });
        this.Add(new WorldCapitalsItem() { Population = 4.65, Y = 40.44, X = -3.69, Country = @"Spain", Name = @"Madrid" });
        this.Add(new WorldCapitalsItem() { Population = 4.34, Y = -12.07, X = -76.82, Country = @"Peru", Name = @"Lima" });
        this.Add(new WorldCapitalsItem() { Population = 4.26, Y = 4.63, X = -74.08, Country = @"Colombia", Name = @"Bogota" });
        this.Add(new WorldCapitalsItem() { Population = 4.1, Y = -33.48, X = -70.65, Country = @"Chile", Name = @"Santiago" });
        this.Add(new WorldCapitalsItem() { Population = 3.84, Y = 33.33, X = 44.4, Country = @"Iraq", Name = @"Baghdad" });
        this.Add(new WorldCapitalsItem() { Population = 3.8, Y = 6.45, X = 3.3, Country = @"Nigeria", Name = @"Lagos" });
        this.Add(new WorldCapitalsItem() { Population = 3.6, Y = 10.5, X = -66.9, Country = @"Venezuela", Name = @"Caracas" });
        this.Add(new WorldCapitalsItem() { Population = 3.43, Y = 23.71, X = 90.41, Country = @"Bangladesh", Name = @"Dhaka" });
        this.Add(new WorldCapitalsItem() { Population = 3.22, Y = 38.89, X = -76.95, Country = @"US", Name = @"Washington D.C." });
        this.Add(new WorldCapitalsItem() { Population = 3.17, Y = 41.88, X = 12.52, Country = @"Italy", Name = @"Roma" });
        this.Add(new WorldCapitalsItem() { Population = 3.03, Y = 38.12, X = 23.65, Country = @"Greece", Name = @"Athens" });
        this.Add(new WorldCapitalsItem() { Population = 3, Y = -4.39, X = 15.47, Country = @"Zaire", Name = @"Kinshasa" });
        this.Add(new WorldCapitalsItem() { Population = 2.9, Y = 50.45, X = 30.5, Country = @"Ukraine", Name = @"Kiev" });
        this.Add(new WorldCapitalsItem() { Population = 2.8, Y = 16.87, X = 96.12, Country = @"Burma", Name = @"Rangoon" });
        this.Add(new WorldCapitalsItem() { Population = 2.56, Y = 47.51, X = 19.09, Country = @"Hungary", Name = @"Budapest" });
        this.Add(new WorldCapitalsItem() { Population = 2.55, Y = 36.6, X = 2.99, Country = @"Algeria", Name = @"Algiers" });
        this.Add(new WorldCapitalsItem() { Population = 2.4, Y = 39.93, X = 32.85, Country = @"Turkey", Name = @"Ankara" });
        this.Add(new WorldCapitalsItem() { Population = 2.38, Y = 50.84, X = 4.37, Country = @"Belgium", Name = @"Bruxelles" });
        this.Add(new WorldCapitalsItem() { Population = 2.33, Y = 41.25, X = 69.35, Country = @"Uzbekistan", Name = @"Toshkent" });
        this.Add(new WorldCapitalsItem() { Population = 2.32, Y = 52.24, X = 21.01, Country = @"Poland", Name = @"Warsaw" });
        this.Add(new WorldCapitalsItem() { Population = 2.25, Y = 38.73, X = -9.13, Country = @"Portugal", Name = @"Lisboa" });
        this.Add(new WorldCapitalsItem() { Population = 2.25, Y = 44.43, X = 26.12, Country = @"Romania", Name = @"Bucharest" });
        this.Add(new WorldCapitalsItem() { Population = 2.13, Y = 23.05, X = -82.42, Country = @"Cuba", Name = @"Havana" });
        this.Add(new WorldCapitalsItem() { Population = 2.05, Y = 7.02, X = 80.09, Country = @"Sri Lanka", Name = @"Colombo" });
        this.Add(new WorldCapitalsItem() { Population = 2.02, Y = 40.32, X = 49.82, Country = @"Azerbaijan", Name = @"Baku" });
        this.Add(new WorldCapitalsItem() { Population = 1.95, Y = 5.32, X = -4.02, Country = @"Ivory Coast", Name = @"Abidjan" });
        this.Add(new WorldCapitalsItem() { Population = 1.88, Y = 48.2, X = 16.32, Country = @"Austria", Name = @"Vienna" });
        this.Add(new WorldCapitalsItem() { Population = 1.86, Y = 52.37, X = 4.89, Country = @"Netherlands", Name = @"Amsterdam" });
        this.Add(new WorldCapitalsItem() { Population = 1.85, Y = 33.52, X = 36.31, Country = @"Syria", Name = @"Damascus" });
        this.Add(new WorldCapitalsItem() { Population = 1.77, Y = 18.4, X = -66.08, Country = @"Puerto Rico", Name = @"San Juan" });
        this.Add(new WorldCapitalsItem() { Population = 1.69, Y = 55.72, X = 12.55, Country = @"Denmark", Name = @"Kobenhavn" });
        this.Add(new WorldCapitalsItem() { Population = 1.68, Y = 33.78, X = 35.66, Country = @"Lebanon", Name = @"Beirut" });
        this.Add(new WorldCapitalsItem() { Population = 1.67, Y = 31.92, X = 34.86, Country = @"Israel", Name = @"Tel Aviv-Yafo" });
        this.Add(new WorldCapitalsItem() { Population = 1.65, Y = 53.9, X = 27.58, Country = @"Belarus", Name = @"Minsk" });
        this.Add(new WorldCapitalsItem() { Population = 1.6, Y = 39.03, X = 125.76, Country = @"North Korea", Name = @"Pyongyang" });
        this.Add(new WorldCapitalsItem() { Population = 1.57, Y = -15.79, X = -47.9, Country = @"Brazil", Name = @"Brasilia" });
        this.Add(new WorldCapitalsItem() { Population = 1.55, Y = -34.92, X = -56.17, Country = @"Uruguay", Name = @"Montevideo" });
        this.Add(new WorldCapitalsItem() { Population = 1.5, Y = 9.03, X = 38.7, Country = @"Ethiopia", Name = @"Adis Abeba" });
        this.Add(new WorldCapitalsItem() { Population = 1.5, Y = 21.03, X = 105.82, Country = @"Vietnam", Name = @"Hanoi" });
        this.Add(new WorldCapitalsItem() { Population = 1.48, Y = 3.15, X = 101.71, Country = @"Malaysia", Name = @"Kuala Lumpur" });
        this.Add(new WorldCapitalsItem() { Population = 1.46, Y = -9, X = 13.46, Country = @"Angola", Name = @"Luanda" });
        this.Add(new WorldCapitalsItem() { Population = 1.46, Y = 41.72, X = 44.78, Country = @"Georgia", Name = @"Tbilisi" });
        this.Add(new WorldCapitalsItem() { Population = 1.45, Y = 59.24, X = 18.08, Country = @"Sweden", Name = @"Stockholm" });
        this.Add(new WorldCapitalsItem() { Population = 1.43, Y = 14.63, X = -16.85, Country = @"Senegal", Name = @"Dakar" });
        this.Add(new WorldCapitalsItem() { Population = 1.4, Y = 14.62, X = -90.52, Country = @"Guatemala", Name = @"Guatemala" });
        this.Add(new WorldCapitalsItem() { Population = 1.4, Y = 44.8, X = 20.41, Country = @"Serbia", Name = @"Belgrade" });
        this.Add(new WorldCapitalsItem() { Population = 1.38, Y = 29.19, X = 48, Country = @"Kuwait", Name = @"Al Kuwayt" });
        this.Add(new WorldCapitalsItem() { Population = 1.32, Y = 50.11, X = 14.46, Country = @"Czechia", Name = @"Prague" });
        this.Add(new WorldCapitalsItem() { Population = 1.31, Y = 18.5, X = -69.91, Country = @"Dominican Rp", Name = @"Santo Domingo" });
        this.Add(new WorldCapitalsItem() { Population = 1.31, Y = 40.21, X = 44.53, Country = @"Armenia", Name = @"Yerevan" });
        this.Add(new WorldCapitalsItem() { Population = 1.3, Y = -6.82, X = 39.25, Country = @"Tanzania", Name = @"Dar es Salaam" });
        this.Add(new WorldCapitalsItem() { Population = 1.29, Y = -1.17, X = 36.83, Country = @"Kenya", Name = @"Nairobi" });
        this.Add(new WorldCapitalsItem() { Population = 1.25, Y = 24.65, X = 46.77, Country = @"Saudi Arabia", Name = @"Ar Riyad" });
        this.Add(new WorldCapitalsItem() { Population = 1.25, Y = 5.56, X = -0.2, Country = @"Ghana", Name = @"Accra" });
        this.Add(new WorldCapitalsItem() { Population = 1.25, Y = 31.95, X = 35.93, Country = @"Jordan", Name = @"Amman" });
        this.Add(new WorldCapitalsItem() { Population = 1.23, Y = 36.82, X = 10.17, Country = @"Tunisia", Name = @"Tunis" });
        this.Add(new WorldCapitalsItem() { Population = 1.21, Y = 42.71, X = 23.33, Country = @"Bulgaria", Name = @"Sofia" });
        this.Add(new WorldCapitalsItem() { Population = 1.19, Y = 43.26, X = 76.91, Country = @"Kazakhstan", Name = @"Almaty" });
        this.Add(new WorldCapitalsItem() { Population = 1.18, Y = 34.53, X = 69.14, Country = @"Afghanistan", Name = @"Kabul" });
        this.Add(new WorldCapitalsItem() { Population = 1.14, Y = 53.34, X = -6.26, Country = @"Ireland", Name = @"Dublin" });
        this.Add(new WorldCapitalsItem() { Population = 1.07, Y = -25.96, X = 32.57, Country = @"Mozambique", Name = @"Maputo" });
        this.Add(new WorldCapitalsItem() { Population = 1.05, Y = -0.23, X = -78.52, Country = @"Ecuador", Name = @"Quito" });
        this.Add(new WorldCapitalsItem() { Population = 1, Y = 56.88, X = 24.05, Country = @"Latvia", Name = @"Riga" });
        this.Add(new WorldCapitalsItem() { Population = 0.99, Y = 32.75, X = 13.21, Country = @"Libya", Name = @"Tripoli" });
        this.Add(new WorldCapitalsItem() { Population = 0.99, Y = -16.5, X = -68.15, Country = @"Bolivia", Name = @"La Paz" });
        this.Add(new WorldCapitalsItem() { Population = 0.98, Y = 33.92, X = -6.75, Country = @"Morocco", Name = @"Rabat" });
        this.Add(new WorldCapitalsItem() { Population = 0.96, Y = -25.73, X = 28.22, Country = @"South Africa", Name = @"Pretoria" });
        this.Add(new WorldCapitalsItem() { Population = 0.92, Y = 15.55, X = 32.53, Country = @"Sudan", Name = @"Khartoum" });
        this.Add(new WorldCapitalsItem() { Population = 0.92, Y = 13.7, X = -89.2, Country = @"El Salvador", Name = @"San Salvador" });
        this.Add(new WorldCapitalsItem() { Population = 0.9, Y = 60.2, X = 24.98, Country = @"Finland", Name = @"Helsinki" });
        this.Add(new WorldCapitalsItem() { Population = 0.89, Y = -17.83, X = 31.02, Country = @"Zimbabwe", Name = @"Harare" });
        this.Add(new WorldCapitalsItem() { Population = 0.88, Y = 18.53, X = -72.34, Country = @"Haiti", Name = @"Port-au-Prince" });
        this.Add(new WorldCapitalsItem() { Population = 0.82, Y = 45.37, X = -75.65, Country = @"Canada", Name = @"Ottawa" });
        this.Add(new WorldCapitalsItem() { Population = 0.8, Y = 9.52, X = -12.8, Country = @"Guinea", Name = @"Conakry" });
        this.Add(new WorldCapitalsItem() { Population = 0.77, Y = 18.02, X = -76.8, Country = @"Jamaica", Name = @"Kingston" });
        this.Add(new WorldCapitalsItem() { Population = 0.72, Y = 59.93, X = 10.72, Country = @"Norway", Name = @"Oslo" });
        this.Add(new WorldCapitalsItem() { Population = 0.7, Y = -25.22, X = -57.67, Country = @"Paraguay", Name = @"Asuncion" });
        this.Add(new WorldCapitalsItem() { Population = 0.7, Y = 45.81, X = 15.96, Country = @"Croatia", Name = @"Zagreb" });
        this.Add(new WorldCapitalsItem() { Population = 0.7, Y = 11.56, X = 104.91, Country = @"Cambodia", Name = @"Phnom Penh" });
        this.Add(new WorldCapitalsItem() { Population = 0.68, Y = 12.15, X = -86.27, Country = @"Nicaragua", Name = @"Managua" });
        this.Add(new WorldCapitalsItem() { Population = 0.67, Y = 47, X = 28.83, Country = @"Moldova", Name = @"Kishinev" });
        this.Add(new WorldCapitalsItem() { Population = 0.67, Y = 9.93, X = -84.08, Country = @"Costa Rica", Name = @"San Jose" });
        this.Add(new WorldCapitalsItem() { Population = 0.66, Y = -18.87, X = 47.5, Country = @"Madagascar", Name = @"Antananarivo" });
        this.Add(new WorldCapitalsItem() { Population = 0.65, Y = 3.87, X = 11.51, Country = @"Cameroon", Name = @"Yaounde" });
        this.Add(new WorldCapitalsItem() { Population = 0.65, Y = 12.65, X = -7.99, Country = @"Mali", Name = @"Bamako" });
        this.Add(new WorldCapitalsItem() { Population = 0.63, Y = 8.95, X = -79.4, Country = @"Panama", Name = @"Panama" });
        this.Add(new WorldCapitalsItem() { Population = 0.62, Y = 42.88, X = 74.77, Country = @"Kyrgyzstan", Name = @"Frunze" });
        this.Add(new WorldCapitalsItem() { Population = 0.6, Y = 2.04, X = 45.34, Country = @"Somalia", Name = @"Muqdisho" });
        this.Add(new WorldCapitalsItem() { Population = 0.59, Y = 38.63, X = 68.9, Country = @"Tajikistan", Name = @"Dushanfe" });
        this.Add(new WorldCapitalsItem() { Population = 0.59, Y = -4.29, X = 15.29, Country = @"Congo", Name = @"Brazzaville" });
        this.Add(new WorldCapitalsItem() { Population = 0.58, Y = 54.69, X = 25.28, Country = @"Lithuania", Name = @"Vilnius" });
        this.Add(new WorldCapitalsItem() { Population = 0.55, Y = 14.1, X = -87.2, Country = @"Honduras", Name = @"Tegucigalpa" });
        this.Add(new WorldCapitalsItem() { Population = 0.55, Y = 47.93, X = 106.91, Country = @"Mongolia", Name = @"Ulaanbaatar" });
        this.Add(new WorldCapitalsItem() { Population = 0.54, Y = -15.43, X = 28.17, Country = @"Zambia", Name = @"Lusaka" });
        this.Add(new WorldCapitalsItem() { Population = 0.53, Y = 8.38, X = -12.91, Country = @"Sierra Leone", Name = @"Freetown" });
        this.Add(new WorldCapitalsItem() { Population = 0.48, Y = 59.28, X = 24.75, Country = @"Estonia", Name = @"Tallinn" });
        this.Add(new WorldCapitalsItem() { Population = 0.47, Y = 6.52, X = -10.77, Country = @"Liberia", Name = @"Monrovia" });
        this.Add(new WorldCapitalsItem() { Population = 0.47, Y = 4.37, X = 18.56, Country = @"Cent Af Rep", Name = @"Bangui" });
        this.Add(new WorldCapitalsItem() { Population = 0.46, Y = 0.32, X = 32.58, Country = @"Uganda", Name = @"Kampala" });
        this.Add(new WorldCapitalsItem() { Population = 0.45, Y = 42, X = 21.53, Country = @"Macedonia", Name = @"Skopje" });
        this.Add(new WorldCapitalsItem() { Population = 0.44, Y = 12.48, X = -1.67, Country = @"Burkina Faso", Name = @"Ouagadouou" });
        this.Add(new WorldCapitalsItem() { Population = 0.43, Y = 48.27, X = 17.27, Country = @"Slovakia", Name = @"Bratislava" });
        this.Add(new WorldCapitalsItem() { Population = 0.43, Y = 15.36, X = 44.21, Country = @"Yemen", Name = @"Sanaa" });
        this.Add(new WorldCapitalsItem() { Population = 0.4, Y = 6.28, X = 1.35, Country = @"Togo", Name = @"Lome" });
        this.Add(new WorldCapitalsItem() { Population = 0.4, Y = 13.6, X = 2.08, Country = @"Niger", Name = @"Niamey" });
        this.Add(new WorldCapitalsItem() { Population = 0.4, Y = 37.95, X = 58.39, Country = @"Turkmenistan", Name = @"Ashkhabad" });
        this.Add(new WorldCapitalsItem() { Population = 0.38, Y = 18, X = 102.68, Country = @"Laos", Name = @"Vientiane" });
        this.Add(new WorldCapitalsItem() { Population = 0.37, Y = 10.64, X = -61.49, Country = @"Trinidad", Name = @"Port of Spain" });
        this.Add(new WorldCapitalsItem() { Population = 0.35, Y = -41.21, X = 175.14, Country = @"New Zealand", Name = @"Wellington" });
        this.Add(new WorldCapitalsItem() { Population = 0.34, Y = 43.87, X = 18.43, Country = @"Bosnia", Name = @"Sarajevo" });
        this.Add(new WorldCapitalsItem() { Population = 0.32, Y = 27.71, X = 85.31, Country = @"Nepal", Name = @"Kathmandu" });
        this.Add(new WorldCapitalsItem() { Population = 0.31, Y = 25.2, X = 51.5, Country = @"Qatar", Name = @"Doha" });
        this.Add(new WorldCapitalsItem() { Population = 0.3, Y = 12.1, X = 15.24, Country = @"Chad", Name = @"N'Djamena" });
        this.Add(new WorldCapitalsItem() { Population = 0.3, Y = 46.95, X = 7.45, Country = @"Switzerland", Name = @"Bern" });
        this.Add(new WorldCapitalsItem() { Population = 0.28, Y = 18.03, X = -15.78, Country = @"Mauritania", Name = @"Nouakchott" });
        this.Add(new WorldCapitalsItem() { Population = 0.28, Y = 15.33, X = 38.97, Country = @"Eritrea", Name = @"Asmara" });
        this.Add(new WorldCapitalsItem() { Population = 0.27, Y = -3.27, X = 29.53, Country = @"Burundi", Name = @"Bujumbura" });
        this.Add(new WorldCapitalsItem() { Population = 0.27, Y = -35.35, X = 149.04, Country = @"Australia", Name = @"Canberra" });
        this.Add(new WorldCapitalsItem() { Population = 0.27, Y = 28.57, X = 77.22, Country = @"India", Name = @"New Delhi" });
        this.Add(new WorldCapitalsItem() { Population = 0.24, Y = 24.24, X = 54.62, Country = @"UAE", Name = @"Abu Zaby" });
        this.Add(new WorldCapitalsItem() { Population = 0.24, Y = 5.93, X = -55.23, Country = @"SuriName", Name = @"Paramaribo" });
        this.Add(new WorldCapitalsItem() { Population = 0.24, Y = -0.5, X = 9.49, Country = @"Gabon", Name = @"Libreville" });
        this.Add(new WorldCapitalsItem() { Population = 0.23, Y = -13.92, X = 33.82, Country = @"Malawi", Name = @"LiXgwe" });
        this.Add(new WorldCapitalsItem() { Population = 0.23, Y = 46.07, X = 14.64, Country = @"Slovenia", Name = @"Ljubljana" });
        this.Add(new WorldCapitalsItem() { Population = 0.21, Y = 41.33, X = 19.83, Country = @"Albania", Name = @"Tirane" });
        this.Add(new WorldCapitalsItem() { Population = 0.2, Y = 33.72, X = 73.06, Country = @"Pakistan", Name = @"Islamabad" });
        this.Add(new WorldCapitalsItem() { Population = 0.19, Y = 6.77, X = -58.17, Country = @"Guyana", Name = @"Georgetown" });
        this.Add(new WorldCapitalsItem() { Population = 0.18, Y = -2.12, X = 29.99, Country = @"Rwanda", Name = @"Kigali" });
        this.Add(new WorldCapitalsItem() { Population = 0.18, Y = 35.17, X = 33.39, Country = @"Cyprus", Name = @"Nicosia" });
        this.Add(new WorldCapitalsItem() { Population = 0.16, Y = 6.6, X = 2.63, Country = @"Benin", Name = @"Porto Novo" });
        this.Add(new WorldCapitalsItem() { Population = 0.15, Y = -9.55, X = 147.41, Country = @"Papua N Guin", Name = @"Port Moresby" });
        this.Add(new WorldCapitalsItem() { Population = 0.14, Y = 64.31, X = -21.34, Country = @"Iceland", Name = @"Reykjavik" });
        this.Add(new WorldCapitalsItem() { Population = 0.13, Y = 49.74, X = 6.27, Country = @"Luxembourg", Name = @"Luxembourg" });
        this.Add(new WorldCapitalsItem() { Population = 0.12, Y = -22.57, X = 17.1, Country = @"Namibia", Name = @"Windhoek" });
        this.Add(new WorldCapitalsItem() { Population = 0.12, Y = 11.5, X = 43.1, Country = @"Djibouti", Name = @"Djibouti" });
        this.Add(new WorldCapitalsItem() { Population = 0.11, Y = 11.91, X = -15.65, Country = @"GuineaBissau", Name = @"Bissau" });
        this.Add(new WorldCapitalsItem() { Population = 0.11, Y = -29.26, X = 27.89, Country = @"Lesotho", Name = @"Maseru" });
        this.Add(new WorldCapitalsItem() { Population = 0.1, Y = 13.45, X = -16.49, Country = @"Gambia", Name = @"Banjul" });
        this.Add(new WorldCapitalsItem() { Population = 0.1, Y = -24.66, X = 25.79, Country = @"Botswana", Name = @"Gaborone" });
        this.Add(new WorldCapitalsItem() { Population = 0.08, Y = 42.5, X = 19.4, Country = @"Montenegro", Name = @"Podgorica" });
        this.Add(new WorldCapitalsItem() { Population = 0.06, Y = 4.93, X = 114.97, Country = @"Brunei", Name = @"Bandar Seri Begawan" });
        this.Add(new WorldCapitalsItem() { Population = 0.05, Y = 23.52, X = 58.63, Country = @"Oman", Name = @"Masqat" });
        this.Add(new WorldCapitalsItem() { Population = 0.04, Y = 4.92, X = -52.4, Country = @"Fr Guiana", Name = @"Cayenne" });
        this.Add(new WorldCapitalsItem() { Population = 0.04, Y = -26.3, X = 31.19, Country = @"Swaziland", Name = @"Mbabne" });
        this.Add(new WorldCapitalsItem() { Population = 0.03, Y = 3.64, X = 8.82, Country = @"Eq Guinea", Name = @"Malabo" });
        this.Add(new WorldCapitalsItem() { Population = 0.01, Y = 17.12, X = -88.8, Country = @"Belize", Name = @"Belmopan" });
        this.Add(new WorldCapitalsItem() { Population = 0.01, Y = 64.27, X = -51.58, Country = @"Greenland", Name = @"Godthab" });
        this.Add(new WorldCapitalsItem() { Population = 0.01, Y = 27.44, X = 89.67, Country = @"Bhutan", Name = @"Thimbu" });
    }
}
