// AUTO-GENERATED by scripts/ingest-samples.ps1 — DO NOT EDIT MANUALLY.
// Run the ingest script to regenerate this file after adding or removing samples.

using System;
using System.Collections.Generic;

namespace SamplesBrowser;

public static class SampleRegistry
{
    /// <summary>
    /// Maps a sample route (e.g. "charts/category-chart/overview") to a factory
    /// that creates the corresponding sample UserControl.
    /// Populated by scripts/ingest-samples.ps1.
    /// </summary>
    public static readonly Dictionary<string, Func<object>> Samples = new()
    {
        { "charts/category-chart/animation", () => new Pages.Charts.CategoryChart.Animation.Sample() },
        { "charts/category-chart/overview", () => new Pages.Charts.CategoryChart.Overview.Sample() },
        { "gauges/radial-gauge/overview", () => new Pages.Gauges.RadialGauge.Overview.Sample() },
    };
}
